
#FROM python:3.6-slim
FROM smizy/scikit-learn
#FROM smizy/python:3.6.3-alpine

#RUN pip3 install --upgrade pip
##RUN apk update
#
#RUN set -x \
#    && apk update \
#    && apk --no-cache add \
#        freetype \
#        openblas \
#        py3-zmq \
#        tini \
#    && ln -s /usr/include/locale.h /usr/include/xlocale.h \
#    && apk --no-cache add --virtual .builddeps \
#        build-base \
#        freetype-dev \
#        gfortran \
#        openblas-dev \
#        pkgconf \
#        python3-dev

RUN apk add --virtual build-dependencies build-base gcc wget git cmake make
RUN apk --update add openjdk7-jre

RUN mkdir automl
COPY . /code/automl

#XGBoost installation
RUN git clone --recursive https://github.com/dmlc/xgboost

RUN cd xgboost && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j4

RUN rm -rf xgboost

#Python dependencies
RUN pip3 install numpy
RUN pip3 install -r /code/automl/requirements.txt
RUN pip3 install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

#CMD ["jupyter-lab"]
